services:
  sveltekit-app:
    container_name: sveltekit-app
    restart: unless-stopped
    command: npm run dev -- --host
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env.dev
    volumes:
      - ./src:/app/src
      - ./static:/app/static
  
  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5444:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    

  